name: retail_dx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  package_info: ^2.0.2
  google_fonts: 6.1.0
  flutter_localization: ^0.2.0
  gap: ^3.0.1
  url_launcher: ^6.1.14
  hexcolor: ^3.0.1
  geolocator: ^11.0.0
  lottie: ^2.6.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  google_maps_flutter_web: ^0.5.4+1
  cloud_functions: ^4.6.0
  pointer_interceptor: ^0.9.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/lottie/
    - assets/maps/
    - assets/fonts/